### ISSUE TITLE
line continuations in truffleHogRegexes/regexes.json

### ISSUE THREAD

**Issue by mpechner** [dxa4481/truffleHogRegexes#15]
What version of the json library are you using in what environment.

I am using latest brew for python3.  Does not seem to like the multiline strings.

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 4 column 66 (char 205)

**Comment by dxa4481** [comment]
Hey thanks for catching this. I merged some new secrets in recently, but hadn't had a chance to test them out yet. I probably should have merged them into a dev branch.
I didn't strike a new release in pypi, but it still would break for folks pulling directly from the repo. I think I fixed the issues. Let me know if there's more problems, or feel free to close this issue if it's resolved

**Comment by mpechner** [comment]
That fixed it.
